"use client";

import React from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { ArrowRight, FileText, ShieldAlert, ShieldCheck, Key } from "lucide-react";

interface TrustData {
  title: string;
  tag: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  tagline: string;
  description: string;
  clauses: string[];
  ctaText: string;
  ctaHref: string;
}

const TRUST_MAP: Record<string, TrustData> = {
  "privacy": {
    title: "Privacy Policy",
    tag: "Trust",
    icon: ShieldCheck,
    tagline: "Your research and portfolio data are secure and entirely private.",
    description: "At OnDecide, we believe your research and investment history belong solely to you. We do not sell your personal details, watchlist configurations, or search queries to market makers, brokers, or external advertising syndicates.",
    clauses: [
      "No selling of user data or personal information.",
      "Clerk securely handles all authentication loops.",
      "Research history is encrypted during session transfers."
    ],
    ctaText: "Open Legal Center",
    ctaHref: "/legal",
  },
  "terms": {
    title: "Terms of Service",
    tag: "Terms",
    icon: FileText,
    tagline: "Understand the parameters governing the use of OnDecide.",
    description: "Our Terms of Service outline the boundaries of user access. We require all API calls and frontend screens to respect our security firewalls and rate limit bounds (10 requests per 10 seconds).",
    clauses: [
      "Suspending accounts that bypass security firewalls.",
      "Users agree that AI ratings are educational only.",
      "Strict prohibition of commercial web-scraping pipelines."
    ],
    ctaText: "Open Legal Center",
    ctaHref: "/legal",
  },
  "disclaimers": {
    title: "Security Disclaimers",
    tag: "Regulatory",
    icon: ShieldAlert,
    tagline: "AI recommendations are not licensed financial advice.",
    description: "OnDecide is not a registered investment advisor, broker, or dealer. The automated findings (Invest, Hold, Avoid) generated by our Gemini agent chains are based on mathematical ratios, technical oscillators, and crawled news. Perform your own diligence or consult a certified advisor before committing capital.",
    clauses: [
      "Ratings are completely automated from public filings.",
      "We cannot guarantee 100% accuracy of third-party data APIs.",
      "Past performance is not indicative of future market results."
    ],
    ctaText: "Open Legal Center",
    ctaHref: "/legal",
  },
  "data-partners": {
    title: "Data Partners",
    tag: "Partnerships",
    icon: Key,
    tagline: "Verifiable feeds from industry-leading integrations.",
    description: "We partner with trusted financial API platforms to ensure the data fueling our reports remains accurate and robust. Our core feeds cover SEC EDGAR filings, Finnhub candles, and Tavily queries.",
    clauses: [
      "Finnhub Stock and ETF candle feeds.",
      "Tavily Search Engine for sentiment news.",
      "SEC EDGAR database for 10-K and 10-Q filing audits."
    ],
    ctaText: "About Our Story",
    ctaHref: "/about",
  },
};

export default function TrustDetailPage({ params }: { params: { slug: string } }) {
  const trust = TRUST_MAP[params.slug];

  if (!trust) {
    notFound();
  }

  const IconComponent = trust.icon;

  return (
    <div className="max-w-5xl mx-auto px-6 py-16">
      {/* Back Link */}
      <Link href="/legal" className="inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-white transition-colors mb-8 font-sans">
        <ArrowRight className="w-3 h-3 rotate-180" /> Back to Trust Center
      </Link>

      {/* Main Grid */}
      <div className="grid md:grid-cols-[1.5fr_1fr] gap-12 items-start">
        {/* Left Informational Content */}
        <div className="space-y-8">
          <div className="space-y-3">
            <span className="text-2xs text-zinc-500 font-sans tracking-wider uppercase block">{trust.tag}</span>
            <h1 className="text-4xl sm:text-5xl font-serif text-white">{trust.title}</h1>
            <p className="text-zinc-400 text-lg leading-relaxed">{trust.tagline}</p>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-serif text-white">Overview</h2>
            <p className="text-zinc-400 text-sm leading-relaxed">{trust.description}</p>
          </div>
        </div>

        {/* Right Sidebar Details */}
        <div className="space-y-6">
          <div className="border border-zinc-800 bg-zinc-950 rounded-lg p-6 flex flex-col items-center text-center space-y-4 min-h-[220px]">
            <div className="w-12 h-12 rounded bg-zinc-900 border border-zinc-800 flex items-center justify-center">
              <IconComponent className="w-6 h-6 text-white stroke-1" />
            </div>
            <h3 className="text-lg font-serif text-white">{trust.title}</h3>
            <p className="text-xs text-zinc-500 max-w-[200px]">
              Ready to learn more? Visit the main trust portal.
            </p>
            <Link href={trust.ctaHref} className="w-full">
              <Button className="w-full bg-zinc-100 hover:bg-white text-black text-xs font-semibold py-2.5 rounded transition-colors">
                {trust.ctaText}
              </Button>
            </Link>
          </div>

          <div className="border border-zinc-850 p-6 rounded space-y-4">
            <h4 className="text-xs text-zinc-500 font-sans tracking-wider uppercase">Key Clauses</h4>
            <ul className="space-y-2">
              {trust.clauses.map((c) => (
                <li key={c} className="text-xs text-zinc-300 font-sans flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-white" />
                  {c}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
